"""Persistence contract for KP-private random-resolution receipts."""

from typing import Protocol


class PrivateRandomResolutionStore(Protocol):
    def begin_immediate(self) -> None: ...

    def get_campaign(self, campaign_id: str) -> dict: ...

    def npc_is_linked_to_campaign(self, campaign_id: str, npc_id: str) -> bool: ...

    def get_npc_availability_profile(self, npc_id: str) -> dict | None: ...

    def get_campaign_npc_reappearance_policy(self, campaign_id: str) -> dict: ...

    def begin_private_random_resolution(self) -> None: ...

    def finish_private_random_resolution(self) -> None: ...

    def rollback_private_random_resolution(self) -> None: ...

    def find_npc_hidden_appearance_resolution(
        self, campaign_id: str, idempotency_key: str
    ) -> dict | None: ...

    def create_npc_hidden_appearance_resolution(self, **values) -> dict: ...

    def list_npc_hidden_appearance_resolutions(
        self, campaign_id: str, limit: int = 50
    ) -> list[dict]: ...

    def list_travel_locations(self, campaign_id: str) -> list[dict]: ...

    def list_travel_routes(self, campaign_id: str) -> list[dict]: ...


__all__ = ["PrivateRandomResolutionStore"]
