"""Persistence contract for ruleset-neutral campaign world entities."""

from typing import Any, Protocol


class WorldEntityStore(Protocol):
    def get_campaign_world_entity(self, entity_id: str) -> dict: ...

    def find_campaign_world_entity_by_origin(
        self,
        campaign_id: str,
        origin_kind: str,
        origin_ref: str,
    ) -> dict | None: ...

    def create_campaign_world_entity(self, **values: Any) -> dict: ...

    def create_campaign_world_entity_relation(self, **values: Any) -> dict: ...

    def list_campaign_world_entity_states(self, campaign_id: str) -> list[dict]: ...

    def get_campaign_world_entity_state(
        self, entity_id: str, dimension: str
    ) -> dict | None: ...

    def create_npc(self, **values: Any) -> dict: ...

    def get_npc(self, npc_id: str) -> dict: ...

    def link_npc_to_campaign(self, campaign_id: str, npc_id: str, **values: Any) -> None: ...


class WorldEntityStateStore(WorldEntityStore, Protocol):
    def begin_immediate(self) -> None: ...

    def begin_campaign_world_entity_state_change(self) -> None: ...

    def finish_campaign_world_entity_state_change(self) -> None: ...

    def rollback_campaign_world_entity_state_change(self) -> None: ...

    def is_session_member_active(self, member_id: str, session_id: str) -> bool: ...

    def append_event(self, **values: Any) -> dict: ...

    def append_realtime_event(self, **values: Any) -> dict: ...

    def find_campaign_world_entity_state_change_by_key(
        self, campaign_id: str, idempotency_key: str
    ) -> dict | None: ...

    def list_campaign_world_entity_state_changes(self, campaign_id: str) -> list[dict]: ...

    def bump_campaign_world_entity_state_version(
        self, entity_id: str, expected_version: int
    ) -> bool: ...

    def set_campaign_world_entity_state(self, **values: Any) -> None: ...

    def create_campaign_world_entity_state_change(self, **values: Any) -> dict: ...


__all__ = ["WorldEntityStateStore", "WorldEntityStore"]
