"""Ruleset-neutral entity archetypes for the public-domain US 1920s setting pack.

These records describe capabilities and open relationship slots.  They contain no
identity, scenario fact, clue answer, or game statistic and therefore cannot be
materialized without the shared world-expansion approval path.
"""

from __future__ import annotations

US_1920S_ENTITY_ARCHETYPES = (
    {
        "archetype_id": "civic_record_keeper",
        "entity_kind": "npc",
        "label_variants": ["市政书记员", "档案员", "柜台职员"],
        "applicable_scene_slots": ["civic_center", "local_government"],
        "capability_tags": ["public_records", "certified_copies", "local_procedure"],
        "profession_ids": ["municipal_clerk"],
        "state_dimensions": ["availability", "cooperation", "record_access"],
        "relation_slots": [
            {
                "relation_slot_id": "employer",
                "predicate": "works_for",
                "target_kinds": ["organization"],
                "target_archetype_ids": ["civic_administration"],
                "minimum_count": 1,
                "maximum_count": 1,
            }
        ],
    },
    {
        "archetype_id": "public_safety_officer",
        "entity_kind": "npc",
        "label_variants": ["巡警", "警探", "副警长", "治安官"],
        "applicable_scene_slots": ["law_enforcement", "local_authority", "nearest_services"],
        "capability_tags": ["public_safety", "detention", "case_records"],
        "profession_ids": ["law_officer", "sheriff"],
        "state_dimensions": ["on_duty", "jurisdiction", "cooperation"],
        "relation_slots": [
            {
                "relation_slot_id": "agency",
                "predicate": "serves",
                "target_kinds": ["organization"],
                "target_archetype_ids": ["public_safety_agency"],
                "minimum_count": 1,
                "maximum_count": 1,
            }
        ],
    },
    {
        "archetype_id": "medical_practitioner",
        "entity_kind": "npc",
        "label_variants": ["医生", "护士", "药剂师", "乡村医生"],
        "applicable_scene_slots": ["medical_care", "medical_access", "nearest_services"],
        "capability_tags": ["treatment", "medical_observation", "medical_records"],
        "profession_ids": ["physician", "medical_staff"],
        "state_dimensions": ["availability", "specialty", "confidentiality"],
        "relation_slots": [
            {
                "relation_slot_id": "practice",
                "predicate": "practices_at",
                "target_kinds": ["organization"],
                "target_archetype_ids": ["medical_provider"],
                "minimum_count": 0,
                "maximum_count": 2,
            }
        ],
    },
    {
        "archetype_id": "information_worker",
        "entity_kind": "npc",
        "label_variants": ["记者", "编辑", "图书管理员", "电报员"],
        "applicable_scene_slots": [
            "news_archive", "library_archive", "local_news", "postal_communications",
            "post_and_telegraph",
        ],
        "capability_tags": ["search_records", "local_memory", "communications"],
        "profession_ids": ["journalist", "librarian", "telegraph_operator", "postal_clerk"],
        "state_dimensions": ["availability", "source_trust", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "transport_worker",
        "entity_kind": "npc",
        "label_variants": ["站务员", "售票员", "货运代理", "机械师"],
        "applicable_scene_slots": ["transport_hub", "transport_stop", "route_out", "industrial_district"],
        "capability_tags": ["schedules", "passenger_memory", "cargo_records"],
        "profession_ids": ["transport_agent", "industrial_worker"],
        "state_dimensions": ["shift", "route_knowledge", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "host_or_merchant",
        "entity_kind": "npc",
        "label_variants": ["旅馆经营者", "店主", "柜台职员", "银行职员"],
        "applicable_scene_slots": [
            "lodging", "supplies", "provisions", "banking", "financial_services",
            "main_street", "community_center",
        ],
        "capability_tags": ["customer_memory", "local_gossip", "transaction_records"],
        "profession_ids": ["lodging_keeper", "merchant", "banker"],
        "state_dimensions": ["open_hours", "cooperation", "stock_or_capacity"],
        "relation_slots": [],
    },
    {
        "archetype_id": "community_figure",
        "entity_kind": "npc",
        "label_variants": ["教士", "教师", "社区组织者"],
        "applicable_scene_slots": ["worship", "school", "community_center"],
        "capability_tags": ["family_network", "community_memory", "private_records"],
        "profession_ids": ["clergy", "teacher"],
        "state_dimensions": ["availability", "trust", "community_standing"],
        "relation_slots": [],
    },
    {
        "archetype_id": "rural_local",
        "entity_kind": "npc",
        "label_variants": ["农场主", "佃农", "林场工人", "乡村向导"],
        "applicable_scene_slots": ["homestead", "route_landmark", "natural_site", "community_center"],
        "capability_tags": ["terrain_knowledge", "weather_knowledge", "local_witness"],
        "profession_ids": ["rural_resident"],
        "state_dimensions": ["whereabouts", "trust", "seasonal_work"],
        "relation_slots": [],
    },
    {
        "archetype_id": "civic_administration",
        "entity_kind": "organization",
        "label_variants": ["市政府部门", "镇公所", "县行政办公室"],
        "applicable_scene_slots": ["civic_center", "local_government"],
        "capability_tags": ["governance", "public_records", "permits"],
        "state_dimensions": ["open_hours", "jurisdiction", "record_condition"],
        "relation_slots": [],
    },
    {
        "archetype_id": "public_safety_agency",
        "entity_kind": "organization",
        "label_variants": [
            "市警察部门",
            "镇警察局",
            "小镇警察局",
            "警长办公室",
            "镇警长办公室",
            "巡警驻点",
        ],
        "applicable_scene_slots": ["law_enforcement", "local_authority", "nearest_services"],
        "capability_tags": ["public_safety", "case_management", "detention"],
        "state_dimensions": ["staffing", "jurisdiction", "response_delay"],
        "relation_slots": [],
    },
    {
        "archetype_id": "medical_provider",
        "entity_kind": "organization",
        "label_variants": ["医院", "诊所", "药房", "巡回医疗服务"],
        "applicable_scene_slots": ["medical_care", "medical_access", "nearest_services"],
        "capability_tags": ["treatment", "dispensing", "patient_records"],
        "state_dimensions": ["capacity", "open_hours", "supply_level"],
        "relation_slots": [],
    },
    {
        "archetype_id": "information_institution",
        "entity_kind": "organization",
        "label_variants": ["报社", "图书馆", "历史协会", "邮电机构"],
        "applicable_scene_slots": [
            "news_archive", "library_archive", "local_news", "postal_communications",
            "post_and_telegraph",
        ],
        "capability_tags": ["publishing", "reference", "message_delivery"],
        "state_dimensions": ["open_hours", "collection_scope", "access_policy"],
        "relation_slots": [],
    },
    {
        "archetype_id": "transport_operator",
        "entity_kind": "organization",
        "label_variants": ["铁路公司", "公交运营商", "港务或货运公司"],
        "applicable_scene_slots": ["transport_hub", "transport_stop", "route_out", "industrial_district"],
        "capability_tags": ["scheduled_transport", "cargo_handling", "route_records"],
        "state_dimensions": ["service_status", "schedule", "capacity"],
        "relation_slots": [],
    },
    {
        "archetype_id": "official_register",
        "entity_kind": "document",
        "label_variants": ["地契登记", "税册", "案件登记簿", "拘押记录"],
        "applicable_scene_slots": ["civic_center", "local_government", "law_enforcement", "local_authority"],
        "capability_tags": ["identity_trace", "property_trace", "incident_trace"],
        "state_dimensions": ["completeness", "legibility", "access"],
        "relation_slots": [
            {
                "relation_slot_id": "custodian",
                "predicate": "held_by",
                "target_kinds": ["npc", "organization"],
                "minimum_count": 1,
                "maximum_count": 1,
            }
        ],
    },
    {
        "archetype_id": "communications_record",
        "entity_kind": "document",
        "label_variants": ["电报单", "邮寄登记", "电话留言", "通信副本"],
        "applicable_scene_slots": ["postal_communications", "post_and_telegraph", "community_center"],
        "capability_tags": ["sender_trace", "destination_trace", "time_trace"],
        "state_dimensions": ["completeness", "confidentiality", "delivery_status"],
        "relation_slots": [],
    },
    {
        "archetype_id": "press_or_archive_record",
        "entity_kind": "document",
        "label_variants": ["报纸合订本", "剪报", "城市名录", "地方史档案"],
        "applicable_scene_slots": ["news_archive", "library_archive", "local_news"],
        "capability_tags": ["historical_search", "address_trace", "public_reputation"],
        "state_dimensions": ["date_range", "index_quality", "condition"],
        "relation_slots": [],
    },
    {
        "archetype_id": "medical_record",
        "entity_kind": "document",
        "label_variants": ["病人登记簿", "处方记录", "死亡证明", "值班记录"],
        "applicable_scene_slots": ["medical_care", "medical_access"],
        "capability_tags": ["treatment_trace", "cause_of_death", "visit_trace"],
        "state_dimensions": ["confidentiality", "completeness", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "commercial_record",
        "entity_kind": "document",
        "label_variants": ["销售账簿", "账户账簿", "送货单", "住客登记簿"],
        "applicable_scene_slots": ["lodging", "financial_services", "banking", "supplies", "provisions", "main_street"],
        "capability_tags": ["transaction_trace", "visitor_trace", "supply_trace"],
        "state_dimensions": ["date_range", "completeness", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "schedule_or_manifest",
        "entity_kind": "document",
        "label_variants": ["时刻表", "旅客名单", "货运单", "班次表"],
        "applicable_scene_slots": ["transport_hub", "transport_stop", "route_out", "industrial_district"],
        "capability_tags": ["movement_trace", "cargo_trace", "staffing_trace"],
        "state_dimensions": ["effective_date", "completeness", "service_status"],
        "relation_slots": [],
    },
    {
        "archetype_id": "portable_evidence_object",
        "entity_kind": "item",
        "label_variants": ["遗留物", "工具", "容器", "个人物品"],
        "applicable_scene_slots": [
            "law_enforcement", "industrial_district", "homestead", "route_landmark",
            "natural_site",
        ],
        "capability_tags": ["physical_trace", "ownership_trace", "origin_trace"],
        "state_dimensions": ["condition", "location", "custody"],
        "relation_slots": [],
    },
    {
        "archetype_id": "communication_device",
        "entity_kind": "item",
        "label_variants": ["电话机", "电报设备", "打字机", "无线电接收机"],
        "applicable_scene_slots": ["postal_communications", "post_and_telegraph", "news_archive", "local_news"],
        "capability_tags": ["period_communication", "message_production"],
        "state_dimensions": ["working_order", "line_status", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "scheduled_ground_transport",
        "entity_kind": "vehicle",
        "label_variants": ["列车", "有轨电车", "长途客车"],
        "applicable_scene_slots": ["transport_hub", "transport_stop", "route_out"],
        "capability_tags": ["scheduled_movement", "passenger_transport", "cargo_transport"],
        "state_dimensions": ["schedule_status", "capacity", "condition"],
        "relation_slots": [],
    },
    {
        "archetype_id": "road_vehicle",
        "entity_kind": "vehicle",
        "label_variants": ["私家汽车", "出租汽车", "货车", "警用车辆"],
        "applicable_scene_slots": ["main_street", "law_enforcement", "local_authority", "route_landmark", "homestead"],
        "capability_tags": ["road_movement", "passenger_transport", "cargo_transport"],
        "state_dimensions": ["condition", "fuel", "whereabouts"],
        "relation_slots": [],
    },
    {
        "archetype_id": "water_transport",
        "entity_kind": "vehicle",
        "label_variants": ["渡船", "货船", "小艇"],
        "applicable_scene_slots": ["transport_hub", "industrial_district", "route_out", "natural_site"],
        "capability_tags": ["water_movement", "cargo_transport"],
        "state_dimensions": ["schedule_status", "weather_access", "condition"],
        "relation_slots": [],
    },
    {
        "archetype_id": "scheduled_arrival",
        "entity_kind": "event",
        "label_variants": ["列车到站", "邮车抵达", "船舶靠港", "换班"],
        "applicable_scene_slots": ["transport_hub", "transport_stop", "route_out", "industrial_district"],
        "capability_tags": ["gather_witnesses", "change_availability", "move_entities"],
        "state_dimensions": ["scheduled_time", "delay", "completion"],
        "relation_slots": [],
    },
    {
        "archetype_id": "public_gathering",
        "entity_kind": "event",
        "label_variants": ["公共会议", "礼拜", "集市", "社区集会"],
        "applicable_scene_slots": ["civic_center", "local_government", "worship", "school", "community_center", "main_street"],
        "capability_tags": ["gather_witnesses", "spread_information", "public_conflict"],
        "state_dimensions": ["scheduled_time", "attendance", "disruption"],
        "relation_slots": [],
    },
    {
        "archetype_id": "service_disruption",
        "entity_kind": "event",
        "label_variants": ["线路中断", "断货", "道路受阻", "机构临时关闭"],
        "applicable_scene_slots": ["postal_communications", "post_and_telegraph", "supplies", "provisions", "nearest_services", "route_landmark", "natural_site"],
        "capability_tags": ["delay_access", "redirect_route", "create_pressure"],
        "state_dimensions": ["cause", "duration", "affected_scope"],
        "relation_slots": [],
    },
    {
        "archetype_id": "institutional_incident",
        "entity_kind": "event",
        "label_variants": ["档案争议", "事故", "异常来访", "公开冲突"],
        "applicable_scene_slots": ["law_enforcement", "medical_care", "news_archive", "lodging", "financial_services", "banking", "industrial_district"],
        "capability_tags": ["create_record", "produce_witnesses", "change_access"],
        "state_dimensions": ["occurred_at", "known_to_public", "resolved"],
        "relation_slots": [],
    },
    {
        "archetype_id": "official_record_carrier",
        "entity_kind": "clue_carrier",
        "label_variants": ["官方记录线索载体", "登记索引", "认证副本"],
        "applicable_scene_slots": ["civic_center", "local_government", "law_enforcement", "local_authority"],
        "capability_tags": ["supports_claim", "links_identity", "links_place"],
        "state_dimensions": ["discovery_state", "credibility", "access"],
        "relation_slots": [],
    },
    {
        "archetype_id": "correspondence_carrier",
        "entity_kind": "clue_carrier",
        "label_variants": ["信件", "电报", "留言", "寄件凭据"],
        "applicable_scene_slots": ["postal_communications", "post_and_telegraph", "lodging", "community_center"],
        "capability_tags": ["links_people", "links_time", "links_destination"],
        "state_dimensions": ["discovery_state", "authenticity", "completeness"],
        "relation_slots": [],
    },
    {
        "archetype_id": "published_media_carrier",
        "entity_kind": "clue_carrier",
        "label_variants": ["新闻报道", "公告", "目录条目", "照片"],
        "applicable_scene_slots": ["news_archive", "library_archive", "local_news", "main_street"],
        "capability_tags": ["links_event", "links_reputation", "visual_evidence"],
        "state_dimensions": ["discovery_state", "date", "reliability"],
        "relation_slots": [],
    },
    {
        "archetype_id": "witness_account_carrier",
        "entity_kind": "clue_carrier",
        "label_variants": ["目击证词", "口述记忆", "工作交接说明"],
        "applicable_scene_slots": [
            "lodging", "supplies", "provisions", "worship", "school", "homestead",
            "route_landmark", "natural_site", "transport_hub", "transport_stop",
        ],
        "capability_tags": ["links_event", "links_person", "links_route"],
        "state_dimensions": ["discovery_state", "reliability", "willingness"],
        "relation_slots": [],
    },
)

__all__ = ["US_1920S_ENTITY_ARCHETYPES"]
