"""Small, reviewable built-in setting packs; no proprietary scenario content."""

from __future__ import annotations

from ai_kp.platform.scenes.builtin_us_1920s_entities import (
    US_1920S_ENTITY_ARCHETYPES,
)
from ai_kp.platform.scenes.settlement_templates import SettingPack

US_1920S = SettingPack.model_validate(
    {
        "setting_pack_id": "us.1920s",
        "schema_version": "1",
        "pack_version": "1.0.0",
        "title": "1920 年代美国",
        "locale": "United States",
        "content_scope": "通用历史时代与社会功能模板；不含任何商业规则书或冒险模组文本。",
        "provenance": [
            "United States Census Bureau historical urban/rural classification",
            "Library of Congress historic newspaper directory",
            "National Park Service historic transportation and settlement context",
        ],
        "year_start": 1920,
        "year_end": 1929,
        "era_constraints": {
            "available_technologies": [
                "landline telephone",
                "telegraph",
                "radio broadcast",
                "typewriter",
                "film camera",
                "motorcar",
                "electric lighting",
            ],
            "unavailable_technologies": [
                "internet",
                "mobile telephone",
                "satellite navigation",
                "CCTV",
                "digital database",
                "DNA profiling",
                "modern emergency dispatch",
            ],
            "common_transport": [
                "walking",
                "motorcar",
                "streetcar",
                "railway",
                "motor coach",
                "ship",
            ],
            "common_communications": [
                "postal mail",
                "telegram",
                "landline call",
                "newspaper",
                "radio",
            ],
            "record_media": [
                "paper ledger",
                "card index",
                "city directory",
                "newspaper clipping",
                "photograph",
                "typed correspondence",
            ],
            "cautions": [
                "具体机构、法律权限和营业时间随州、县、城市规模而变化。",
                "不要把现代数字检索、即时定位或现代法证能力写入场景。",
                "社会偏见可作为历史背景处理，但不得强迫玩家承受未经同意的歧视内容。",
            ],
        },
        "region_patterns": [
            {
                "pattern_id": "metropolitan_satellites",
                "title": "城市与卫星聚落",
                "applicability_tags": ["metropolitan", "mixed_urban_rural"],
                "nodes": [
                    {
                        "node_role": "hub",
                        "settlement_kind": "city",
                        "minimum_count": 1,
                        "maximum_count": 1,
                    },
                    {
                        "node_role": "nearby",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 3,
                    },
                    {
                        "node_role": "distant",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 2,
                    },
                    {
                        "node_role": "rural",
                        "settlement_kind": "rural",
                        "minimum_count": 1,
                        "maximum_count": 5,
                    },
                ],
                "routes": [
                    {
                        "from_role": "hub",
                        "to_role": "nearby",
                        "travel_modes": ["motorcar", "streetcar", "railway"],
                        "distance_band": "near",
                    },
                    {
                        "from_role": "hub",
                        "to_role": "distant",
                        "travel_modes": ["motorcar", "railway"],
                        "distance_band": "regional",
                    },
                    {
                        "from_role": "nearby",
                        "to_role": "rural",
                        "travel_modes": ["motorcar", "walking"],
                        "distance_band": "near",
                    },
                ],
            },
            {
                "pattern_id": "county_town_network",
                "title": "县城、村镇与乡村腹地",
                "applicability_tags": ["inland", "agricultural", "county"],
                "nodes": [
                    {
                        "node_role": "hub",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 1,
                    },
                    {
                        "node_role": "nearby",
                        "settlement_kind": "village",
                        "minimum_count": 1,
                        "maximum_count": 4,
                    },
                    {
                        "node_role": "distant",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 2,
                    },
                    {
                        "node_role": "rural",
                        "settlement_kind": "rural",
                        "minimum_count": 2,
                        "maximum_count": 8,
                    },
                ],
                "routes": [
                    {
                        "from_role": "hub",
                        "to_role": "nearby",
                        "travel_modes": ["motorcar", "walking"],
                        "distance_band": "near",
                    },
                    {
                        "from_role": "hub",
                        "to_role": "distant",
                        "travel_modes": ["motorcar", "railway"],
                        "distance_band": "regional",
                    },
                    {
                        "from_role": "nearby",
                        "to_role": "rural",
                        "travel_modes": ["motorcar", "walking"],
                        "distance_band": "local",
                    },
                ],
            },
            {
                "pattern_id": "rail_corridor",
                "title": "铁路走廊聚落链",
                "applicability_tags": ["rail", "industrial", "linear"],
                "nodes": [
                    {
                        "node_role": "hub",
                        "settlement_kind": "city",
                        "minimum_count": 1,
                        "maximum_count": 1,
                    },
                    {
                        "node_role": "nearby",
                        "settlement_kind": "town",
                        "minimum_count": 2,
                        "maximum_count": 5,
                    },
                    {
                        "node_role": "distant",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 3,
                    },
                    {
                        "node_role": "rural",
                        "settlement_kind": "rural",
                        "minimum_count": 1,
                        "maximum_count": 4,
                    },
                ],
                "routes": [
                    {
                        "from_role": "hub",
                        "to_role": "nearby",
                        "travel_modes": ["railway", "motorcar"],
                        "distance_band": "regional",
                    },
                    {
                        "from_role": "hub",
                        "to_role": "distant",
                        "travel_modes": ["railway"],
                        "distance_band": "remote",
                    },
                    {
                        "from_role": "nearby",
                        "to_role": "rural",
                        "travel_modes": ["motorcar", "walking"],
                        "distance_band": "near",
                    },
                ],
            },
            {
                "pattern_id": "isolated_rural",
                "title": "孤立乡村网络",
                "applicability_tags": ["remote", "mountain", "forest"],
                "nodes": [
                    {
                        "node_role": "hub",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 1,
                    },
                    {
                        "node_role": "nearby",
                        "settlement_kind": "village",
                        "minimum_count": 1,
                        "maximum_count": 3,
                    },
                    {
                        "node_role": "rural",
                        "settlement_kind": "rural",
                        "minimum_count": 2,
                        "maximum_count": 8,
                    },
                ],
                "routes": [
                    {
                        "from_role": "hub",
                        "to_role": "nearby",
                        "travel_modes": ["motorcar", "walking"],
                        "distance_band": "regional",
                    },
                    {
                        "from_role": "nearby",
                        "to_role": "rural",
                        "travel_modes": ["walking", "motorcar"],
                        "distance_band": "near",
                    },
                ],
            },
            {
                "pattern_id": "port_hinterland",
                "title": "港口与内陆腹地",
                "applicability_tags": ["coastal", "river", "port"],
                "nodes": [
                    {
                        "node_role": "hub",
                        "settlement_kind": "city",
                        "minimum_count": 1,
                        "maximum_count": 1,
                    },
                    {
                        "node_role": "nearby",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 3,
                    },
                    {
                        "node_role": "distant",
                        "settlement_kind": "town",
                        "minimum_count": 1,
                        "maximum_count": 2,
                    },
                    {
                        "node_role": "rural",
                        "settlement_kind": "rural",
                        "minimum_count": 1,
                        "maximum_count": 5,
                    },
                ],
                "routes": [
                    {
                        "from_role": "hub",
                        "to_role": "nearby",
                        "travel_modes": ["ship", "motorcar", "railway"],
                        "distance_band": "near",
                    },
                    {
                        "from_role": "hub",
                        "to_role": "distant",
                        "travel_modes": ["ship", "railway"],
                        "distance_band": "regional",
                    },
                    {
                        "from_role": "nearby",
                        "to_role": "rural",
                        "travel_modes": ["motorcar", "boat", "walking"],
                        "distance_band": "near",
                    },
                ],
            },
        ],
        "settlements": [
            {
                "kind": "city",
                "slots": [
                    {
                        "slot_id": "civic_center",
                        "function": "市政与公共记录",
                        "frequency": "core",
                        "building_variants": ["市政厅", "县政府", "法院与书记官办公室"],
                        "play_affordances": ["查地址与产权", "申请许可", "接触官员"],
                    },
                    {
                        "slot_id": "law_enforcement",
                        "function": "治安与拘押",
                        "frequency": "core",
                        "building_variants": ["市警察局", "警察分局", "县警署"],
                        "play_affordances": ["报案", "查案件记录", "询问巡警"],
                    },
                    {
                        "slot_id": "postal_communications",
                        "function": "邮政与远程通信",
                        "frequency": "core",
                        "building_variants": ["邮局", "电报局", "电话交换所"],
                        "play_affordances": ["追查邮件", "发送电报", "查询通信线索"],
                    },
                    {
                        "slot_id": "transport_hub",
                        "function": "区域交通",
                        "frequency": "core",
                        "building_variants": ["铁路总站", "长途汽车站", "港口客运站"],
                        "play_affordances": ["查时刻表", "追踪旅客", "离开城区"],
                    },
                    {
                        "slot_id": "medical_care",
                        "function": "医疗与死亡记录",
                        "frequency": "core",
                        "building_variants": ["市立医院", "慈善医院", "私人诊所"],
                        "play_affordances": ["治疗", "询问医师", "查死亡记录"],
                    },
                    {
                        "slot_id": "news_archive",
                        "function": "新闻与地方记忆",
                        "frequency": "typical",
                        "building_variants": ["日报社", "晚报社", "报社剪报室"],
                        "play_affordances": ["查旧报", "刊登消息", "接触记者"],
                    },
                    {
                        "slot_id": "library_archive",
                        "function": "公共知识与档案",
                        "frequency": "typical",
                        "building_variants": ["公共图书馆", "历史协会", "大学图书馆"],
                        "play_affordances": ["研究地方史", "查名录", "寻找专家"],
                    },
                    {
                        "slot_id": "lodging",
                        "function": "短期住宿",
                        "frequency": "core",
                        "building_variants": ["市中心旅馆", "廉价旅社", "寄宿公寓"],
                        "play_affordances": ["租房", "询问住客", "监视出入口"],
                    },
                    {
                        "slot_id": "financial_services",
                        "function": "金融与商业信用",
                        "frequency": "typical",
                        "building_variants": ["银行", "信托公司", "当铺"],
                        "play_affordances": ["查交易痕迹", "兑换资金", "评估财物"],
                    },
                    {
                        "slot_id": "supplies",
                        "function": "日常与专业补给",
                        "frequency": "core",
                        "building_variants": ["百货商店", "药房", "五金店"],
                        "play_affordances": ["购买装备", "询问订单", "寻找稀缺用品"],
                    },
                    {
                        "slot_id": "worship",
                        "function": "宗教与社区网络",
                        "frequency": "typical",
                        "building_variants": ["教堂", "犹太会堂", "社区礼拜所"],
                        "play_affordances": ["查登记册", "寻求庇护", "接触社区领袖"],
                    },
                    {
                        "slot_id": "industrial_district",
                        "function": "工业与仓储",
                        "frequency": "conditional",
                        "condition_tags": ["industrial", "port"],
                        "building_variants": ["工厂区", "仓库区", "码头货栈"],
                        "play_affordances": ["追踪货物", "潜入", "寻找工人证词"],
                    },
                ],
            },
            {
                "kind": "town",
                "slots": [
                    {
                        "slot_id": "main_street",
                        "function": "公共生活中心",
                        "frequency": "core",
                        "building_variants": ["主街", "镇中心", "集市街"],
                        "play_affordances": ["打听消息", "观察来往", "找到主要服务"],
                    },
                    {
                        "slot_id": "local_government",
                        "function": "地方行政与记录",
                        "frequency": "core",
                        "building_variants": ["镇公所", "县法院", "书记官办公室"],
                        "play_affordances": ["查地契", "查出生死亡记录", "询问官员"],
                    },
                    {
                        "slot_id": "law_enforcement",
                        "function": "地方治安",
                        "frequency": "core",
                        "building_variants": [
                            "警长办公室",
                            "镇警察局",
                            "小镇警察局",
                            "治安官办公桌",
                        ],
                        "play_affordances": ["报案", "查拘留记录", "请治安人员协助"],
                    },
                    {
                        "slot_id": "post_and_telegraph",
                        "function": "邮政与对外通信",
                        "frequency": "core",
                        "building_variants": ["邮局", "邮局兼杂货店", "电报柜台"],
                        "play_affordances": ["收发邮件", "发送电报", "询问外来者"],
                    },
                    {
                        "slot_id": "provisions",
                        "function": "基本补给",
                        "frequency": "core",
                        "building_variants": ["杂货店", "综合商店", "药房兼日用品店"],
                        "play_affordances": ["采购", "打听本地消息", "查特殊订单"],
                    },
                    {
                        "slot_id": "lodging",
                        "function": "旅客住宿",
                        "frequency": "core",
                        "building_variants": ["小旅馆", "寄宿屋", "酒馆楼上客房"],
                        "play_affordances": ["住宿", "询问过客", "查看登记簿"],
                    },
                    {
                        "slot_id": "medical_access",
                        "function": "基础医疗",
                        "frequency": "core",
                        "building_variants": ["医生诊所", "药剂师", "邻近城镇医院"],
                        "play_affordances": ["治疗", "询问伤情", "获得转诊"],
                        "access_scope": "nearby",
                    },
                    {
                        "slot_id": "worship",
                        "function": "礼拜与社区联系",
                        "frequency": "core",
                        "building_variants": ["教堂", "礼拜堂", "牧师住宅"],
                        "play_affordances": ["查教区记录", "询问家族历史", "接触社区"],
                    },
                    {
                        "slot_id": "local_news",
                        "function": "地方新闻",
                        "frequency": "typical",
                        "building_variants": ["周报社", "印刷铺", "邻近城市报纸代办点"],
                        "play_affordances": ["查旧闻", "发布寻人信息", "询问编辑"],
                    },
                    {
                        "slot_id": "transport_stop",
                        "function": "对外交通",
                        "frequency": "typical",
                        "building_variants": ["火车站", "汽车客运站", "公路加油站"],
                        "play_affordances": ["查抵达记录", "追踪车辆", "前往城市"],
                    },
                    {
                        "slot_id": "banking",
                        "function": "存款与信用",
                        "frequency": "typical",
                        "building_variants": ["地方银行", "信用社", "商店汇款服务"],
                        "play_affordances": ["查财务关系", "兑换支票", "询问抵押"],
                    },
                    {
                        "slot_id": "school",
                        "function": "教育与家庭网络",
                        "frequency": "typical",
                        "building_variants": ["公立学校", "一室学校", "邻镇中学"],
                        "play_affordances": ["查名册", "询问教师", "接触家庭"],
                    },
                ],
            },
            {
                "kind": "village",
                "slots": [
                    {
                        "slot_id": "community_center",
                        "function": "村落公共联系",
                        "frequency": "core",
                        "building_variants": ["十字路口商店", "礼拜堂", "邮政代办点"],
                        "play_affordances": ["打听消息", "取得补给", "寻找向导"],
                    },
                    {
                        "slot_id": "local_authority",
                        "function": "可联系的地方权威",
                        "frequency": "core",
                        "building_variants": ["乡镇治安官", "村镇委员住所", "邻镇警长办公室"],
                        "play_affordances": ["报案", "确认地方规矩", "请求支援"],
                        "access_scope": "nearby",
                    },
                    {
                        "slot_id": "medical_access",
                        "function": "可获得的医疗",
                        "frequency": "core",
                        "building_variants": ["乡村医生", "助产士", "邻镇诊所"],
                        "play_affordances": ["治疗", "询问伤病", "获得转送"],
                        "access_scope": "nearby",
                    },
                    {
                        "slot_id": "route_out",
                        "function": "通往外界的路线",
                        "frequency": "core",
                        "building_variants": ["县道", "铁路招呼站", "渡口"],
                        "play_affordances": ["前往小镇", "追踪来客", "封锁或逃离"],
                    },
                ],
            },
            {
                "kind": "rural",
                "slots": [
                    {
                        "slot_id": "homestead",
                        "function": "居住与生产",
                        "frequency": "core",
                        "building_variants": ["农庄", "牧场", "林场工棚"],
                        "play_affordances": ["询问住户", "搜查附属建筑", "观察土地痕迹"],
                    },
                    {
                        "slot_id": "route_landmark",
                        "function": "道路与方位",
                        "frequency": "core",
                        "building_variants": ["土路岔口", "桥梁", "里程标与加油点"],
                        "play_affordances": ["导航", "伏击或追踪", "判断交通痕迹"],
                    },
                    {
                        "slot_id": "nearest_services",
                        "function": "最近的补给、治安与医疗",
                        "frequency": "core",
                        "building_variants": ["邻近村落", "邻近小镇", "巡回服务路线"],
                        "play_affordances": ["求援", "补给", "转送伤员"],
                        "access_scope": "nearby",
                    },
                    {
                        "slot_id": "natural_site",
                        "function": "自然环境节点",
                        "frequency": "typical",
                        "building_variants": ["林地", "河谷", "采石场", "荒废田地"],
                        "play_affordances": ["追踪", "隐蔽", "发现环境证据"],
                    },
                ],
            },
        ],
        "professions": [
            {
                "profession_id": "municipal_clerk",
                "titles": ["市政书记员", "镇书记员"],
                "institution_functions": ["市政与公共记录"],
                "authority": ["调阅公开登记", "认证副本"],
                "knowledge_domains": ["地契", "税册", "居民登记"],
                "schedule_patterns": ["工作日白天"],
                "relationship_hooks": ["地产商", "法院书记员", "地方官员"],
            },
            {
                "profession_id": "law_officer",
                "titles": ["警探", "巡警", "副警长"],
                "institution_functions": ["治安与拘押", "地方治安"],
                "authority": ["询问", "逮捕", "调阅案件档案"],
                "knowledge_domains": ["案件", "治安事件", "地方人物"],
                "schedule_patterns": ["轮班", "紧急召集"],
                "relationship_hooks": ["检察官", "验尸官", "记者"],
            },
            {
                "profession_id": "sheriff",
                "titles": ["县警长", "治安官"],
                "institution_functions": ["地方治安", "可联系的地方权威"],
                "authority": ["县域治安", "拘押", "组织搜查"],
                "knowledge_domains": ["辖区道路", "居民纠纷", "失踪与犯罪"],
                "schedule_patterns": ["工作日白天", "紧急召集"],
                "relationship_hooks": ["镇书记员", "地方医生", "农场主"],
            },
            {
                "profession_id": "postal_clerk",
                "titles": ["邮政职员", "邮政局长"],
                "institution_functions": ["邮政与远程通信", "邮政与对外通信"],
                "authority": ["处理邮件与汇款"],
                "knowledge_domains": ["地址", "收件习惯", "邮路"],
                "schedule_patterns": ["工作日与周六白天"],
                "relationship_hooks": ["铁路职员", "商店老板", "电报员"],
            },
            {
                "profession_id": "telegraph_operator",
                "titles": ["电报员", "电话接线员"],
                "institution_functions": ["邮政与远程通信"],
                "authority": ["传递通信"],
                "knowledge_domains": ["通信时间", "目的地", "线路中断"],
                "schedule_patterns": ["班次值守"],
                "relationship_hooks": ["邮政职员", "站务员", "旅馆前台"],
            },
            {
                "profession_id": "transport_agent",
                "titles": ["站务员", "售票员", "货运代理"],
                "institution_functions": ["区域交通", "对外交通"],
                "authority": ["售票", "查时刻与货运记录"],
                "knowledge_domains": ["旅客", "班次", "货物"],
                "schedule_patterns": ["按时刻表值班"],
                "relationship_hooks": ["司机", "搬运工", "邮政职员"],
            },
            {
                "profession_id": "physician",
                "titles": ["医生", "外科医师", "乡村医生"],
                "institution_functions": ["医疗与死亡记录", "基础医疗", "可获得的医疗"],
                "authority": ["诊断", "治疗", "签署医疗文件"],
                "knowledge_domains": ["伤病", "死亡原因", "药物"],
                "schedule_patterns": ["门诊白天", "紧急出诊"],
                "relationship_hooks": ["护士", "药剂师", "治安人员"],
            },
            {
                "profession_id": "medical_staff",
                "titles": ["护士", "药剂师", "助产士"],
                "institution_functions": ["医疗与死亡记录", "基础医疗"],
                "authority": ["护理", "配药", "保存部分记录"],
                "knowledge_domains": ["病人来访", "处方", "社区健康"],
                "schedule_patterns": ["轮班或营业时间"],
                "relationship_hooks": ["医生", "家庭成员", "殡仪人员"],
            },
            {
                "profession_id": "journalist",
                "titles": ["记者", "编辑", "印刷工"],
                "institution_functions": ["新闻与地方记忆", "地方新闻"],
                "authority": ["查阅剪报", "采访", "出版"],
                "knowledge_domains": ["旧闻", "流言", "公共人物"],
                "schedule_patterns": ["截稿日前后", "白天采访"],
                "relationship_hooks": ["警探", "摄影师", "市政书记员"],
            },
            {
                "profession_id": "librarian",
                "titles": ["图书管理员", "档案员", "历史协会干事"],
                "institution_functions": ["公共知识与档案"],
                "authority": ["查阅目录", "管理特藏"],
                "knowledge_domains": ["地方史", "家谱", "目录与参考书"],
                "schedule_patterns": ["工作日与部分周末白天"],
                "relationship_hooks": ["教授", "记者", "捐赠者"],
            },
            {
                "profession_id": "lodging_keeper",
                "titles": ["旅馆经理", "前台职员", "寄宿屋主人"],
                "institution_functions": ["短期住宿", "旅客住宿"],
                "authority": ["安排客房", "保管登记簿"],
                "knowledge_domains": ["住客", "来访者", "遗留物"],
                "schedule_patterns": ["长时段值守"],
                "relationship_hooks": ["出租车司机", "警察", "清洁工"],
            },
            {
                "profession_id": "banker",
                "titles": ["银行经理", "出纳员", "信贷员"],
                "institution_functions": ["金融与商业信用", "存款与信用"],
                "authority": ["处理账户与贷款"],
                "knowledge_domains": ["抵押", "商业关系", "付款痕迹"],
                "schedule_patterns": ["工作日白天"],
                "relationship_hooks": ["律师", "地产商", "商人"],
            },
            {
                "profession_id": "merchant",
                "titles": ["店主", "药房老板", "五金商"],
                "institution_functions": ["日常与专业补给", "基本补给"],
                "authority": ["销售与订货"],
                "knowledge_domains": ["顾客", "特殊订单", "本地供货"],
                "schedule_patterns": ["白天至傍晚"],
                "relationship_hooks": ["邮政职员", "送货员", "常客"],
            },
            {
                "profession_id": "clergy",
                "titles": ["牧师", "神父", "拉比", "礼拜所管理员"],
                "institution_functions": ["宗教与社区网络", "礼拜与社区联系"],
                "authority": ["主持仪式", "保管教区记录"],
                "knowledge_domains": ["家庭史", "婚丧", "社区矛盾"],
                "schedule_patterns": ["礼拜日与预约"],
                "relationship_hooks": ["家庭", "慈善组织", "殡仪人员"],
            },
            {
                "profession_id": "teacher",
                "titles": ["教师", "校长", "校务职员"],
                "institution_functions": ["教育与家庭网络"],
                "authority": ["管理名册与学生事务"],
                "knowledge_domains": ["家庭", "儿童", "校史"],
                "schedule_patterns": ["学期工作日"],
                "relationship_hooks": ["家长", "镇书记员", "图书管理员"],
            },
            {
                "profession_id": "industrial_worker",
                "titles": ["工头", "仓库管理员", "码头工人", "机械师"],
                "institution_functions": ["工业与仓储"],
                "authority": ["操作或看管工作区"],
                "knowledge_domains": ["货物", "班次", "机器与事故"],
                "schedule_patterns": ["轮班"],
                "relationship_hooks": ["货运代理", "工会成员", "警察"],
            },
            {
                "profession_id": "rural_resident",
                "titles": ["农场主", "佃农", "林场工人", "乡村向导"],
                "institution_functions": ["居住与生产", "村落公共联系"],
                "authority": ["管理自有土地与设施"],
                "knowledge_domains": ["地形", "天气", "邻里与异常活动"],
                "schedule_patterns": ["随季节与日照"],
                "relationship_hooks": ["商店老板", "乡村医生", "警长"],
            },
        ],
        "entity_archetypes": US_1920S_ENTITY_ARCHETYPES,
        "function_details": [
            {
                "detail_id": "civic_center",
                "interior_zones": ["公共柜台", "书记员办公室", "档案室", "会议室"],
                "profession_ids": ["municipal_clerk"],
                "service_capabilities": ["行政咨询", "认证副本"],
                "record_sources": ["地契", "税册", "选民或居民名册", "许可记录"],
                "access_patterns": ["工作日白天", "受限档案需授权"],
                "investigation_surfaces": ["索引卡", "登记簿", "工作人员记忆"],
                "event_seed_kinds": ["档案缺页", "官员施压", "登记矛盾"],
            },
            {
                "detail_id": "local_government",
                "interior_zones": ["公共柜台", "书记员办公室", "档案柜"],
                "profession_ids": ["municipal_clerk"],
                "service_capabilities": ["地方登记", "行政证明"],
                "record_sources": ["地契", "税册", "出生死亡登记"],
                "access_patterns": ["工作日白天"],
                "investigation_surfaces": ["纸质台账", "当地书记员"],
                "event_seed_kinds": ["记录被转移", "地方关系阻挠"],
            },
            {
                "detail_id": "law_enforcement",
                "interior_zones": ["值班台", "办公室", "案卷室", "拘留室", "证物室"],
                "profession_ids": ["law_officer", "sheriff"],
                "service_capabilities": ["报案", "治安响应", "案件查询"],
                "record_sources": ["报案簿", "逮捕记录", "案卷", "证物登记"],
                "access_patterns": ["持续值守或紧急召集", "案卷和证物受限"],
                "investigation_surfaces": ["值班记录", "巡警证词", "证物链"],
                "event_seed_kinds": ["管辖权争议", "失踪案", "证物异常"],
            },
            {
                "detail_id": "local_authority",
                "interior_zones": ["办公桌", "临时拘留处", "马车或汽车棚"],
                "profession_ids": ["sheriff", "law_officer"],
                "service_capabilities": ["报案", "组织搜查", "联系县城"],
                "record_sources": ["简要案件簿", "通缉通知"],
                "access_patterns": ["可能需要从住处或巡逻中召回"],
                "investigation_surfaces": ["个人笔记", "当地口碑"],
                "event_seed_kinds": ["支援延迟", "熟人关系冲突"],
            },
            {
                "detail_id": "postal_communications",
                "interior_zones": ["公共窗口", "分拣区", "电报台", "线路设备间"],
                "profession_ids": ["postal_clerk", "telegraph_operator"],
                "service_capabilities": ["邮件", "电报", "长途电话"],
                "record_sources": ["投递路线", "汇款记录", "电报时间簿"],
                "access_patterns": ["营业时间", "通信内容受隐私与权限限制"],
                "investigation_surfaces": ["邮戳", "地址变更", "线路日志"],
                "event_seed_kinds": ["延迟邮件", "断线", "错误投递"],
            },
            {
                "detail_id": "post_and_telegraph",
                "interior_zones": ["邮政窗口", "分拣架", "电报柜台"],
                "profession_ids": ["postal_clerk", "telegraph_operator"],
                "service_capabilities": ["邮件", "电报", "汇款"],
                "record_sources": ["邮路", "留局待领记录", "电报发送时间"],
                "access_patterns": ["白天营业"],
                "investigation_surfaces": ["邮戳", "熟客记忆"],
                "event_seed_kinds": ["陌生包裹", "通信中断"],
            },
            {
                "detail_id": "transport_hub",
                "interior_zones": ["售票厅", "候车区", "站台", "行李或货运区", "站务办公室"],
                "profession_ids": ["transport_agent", "industrial_worker"],
                "service_capabilities": ["客运", "行李寄存", "货运"],
                "record_sources": ["时刻表", "售票与行李记录", "货运单"],
                "access_patterns": ["按班次运行", "货运区受限"],
                "investigation_surfaces": ["票根", "站务证词", "遗失物"],
                "event_seed_kinds": ["误点", "失踪旅客", "异常货物"],
            },
            {
                "detail_id": "transport_stop",
                "interior_zones": ["候车处", "售票窗口", "装卸区"],
                "profession_ids": ["transport_agent"],
                "service_capabilities": ["区域客运", "简单货运"],
                "record_sources": ["时刻表", "售票簿", "货运收据"],
                "access_patterns": ["仅班次前后有人值守"],
                "investigation_surfaces": ["票根", "司机与站务员记忆"],
                "event_seed_kinds": ["末班车错过", "陌生来客"],
            },
            {
                "detail_id": "route_out",
                "interior_zones": ["道路节点", "候车或等渡区"],
                "profession_ids": ["transport_agent", "rural_resident"],
                "service_capabilities": ["离开聚落", "获得方向"],
                "record_sources": ["时刻告示", "收费或渡运记录"],
                "access_patterns": ["受天气和班次影响"],
                "investigation_surfaces": ["车辙", "目击者", "遗留物"],
                "event_seed_kinds": ["道路阻断", "班次取消"],
            },
            {
                "detail_id": "medical_care",
                "interior_zones": ["接诊区", "诊室", "病房", "药房", "记录室", "太平间"],
                "profession_ids": ["physician", "medical_staff"],
                "service_capabilities": ["急救", "住院", "诊断", "死亡证明"],
                "record_sources": ["病历", "处方", "入院簿", "死亡记录"],
                "access_patterns": ["急诊持续可联系", "病历受限"],
                "investigation_surfaces": ["伤情", "药物", "医护证词"],
                "event_seed_kinds": ["匿名病人", "异常死因", "药品短缺"],
            },
            {
                "detail_id": "medical_access",
                "interior_zones": ["候诊处", "诊室", "药柜"],
                "profession_ids": ["physician", "medical_staff"],
                "service_capabilities": ["基础治疗", "转诊", "出诊"],
                "record_sources": ["预约簿", "处方", "医生笔记"],
                "access_patterns": ["白天门诊或紧急召唤", "可能需要前往邻镇"],
                "investigation_surfaces": ["伤病模式", "药物购买", "社区记忆"],
                "event_seed_kinds": ["医生外出", "转送延迟"],
            },
            {
                "detail_id": "news_archive",
                "interior_zones": ["编辑部", "记者桌", "剪报室", "印刷间", "摄影暗房"],
                "profession_ids": ["journalist"],
                "service_capabilities": ["查旧报", "采访", "刊登信息"],
                "record_sources": ["合订报纸", "剪报索引", "照片底片", "记者笔记"],
                "access_patterns": ["工作日与截稿时段", "未刊资料需许可"],
                "investigation_surfaces": ["报道差异", "照片背景", "匿名消息源"],
                "event_seed_kinds": ["撤稿", "记者失联", "底片被换"],
            },
            {
                "detail_id": "local_news",
                "interior_zones": ["编辑桌", "印刷区", "剪报架"],
                "profession_ids": ["journalist"],
                "service_capabilities": ["地方新闻", "印刷公告"],
                "record_sources": ["周报", "广告", "讣告", "编辑笔记"],
                "access_patterns": ["截稿日前有人"],
                "investigation_surfaces": ["旧闻", "广告客户", "口述消息"],
                "event_seed_kinds": ["被压下的报道", "匿名来信"],
            },
            {
                "detail_id": "library_archive",
                "interior_zones": ["阅览室", "目录区", "书库", "特藏室", "办公室"],
                "profession_ids": ["librarian"],
                "service_capabilities": ["参考咨询", "地方史研究", "馆际联系"],
                "record_sources": ["卡片目录", "城市名录", "家谱", "地图", "特藏"],
                "access_patterns": ["白天开放", "特藏需申请"],
                "investigation_surfaces": ["目录关联", "借阅记录", "边注"],
                "event_seed_kinds": ["资料误编", "特藏缺失", "研究者竞争"],
            },
            {
                "detail_id": "lodging",
                "interior_zones": ["前台", "大堂", "客房", "后勤区", "登记簿存放处"],
                "profession_ids": ["lodging_keeper"],
                "service_capabilities": ["住宿", "留言", "行李保管"],
                "record_sources": ["住客登记簿", "账单", "钥匙记录", "留言"],
                "access_patterns": ["长时段有人值守", "客房属私人空间"],
                "investigation_surfaces": ["登记签名", "员工目击", "遗留物"],
                "event_seed_kinds": ["假名入住", "无人认领行李", "夜间访客"],
            },
            {
                "detail_id": "financial_services",
                "interior_zones": ["柜台大厅", "经理室", "账房", "保险库"],
                "profession_ids": ["banker"],
                "service_capabilities": ["存取款", "贷款", "保管"],
                "record_sources": ["账户账簿", "抵押文件", "保险箱登记"],
                "access_patterns": ["工作日短时营业", "账户与金库严格受限"],
                "investigation_surfaces": ["付款链", "签名", "抵押关系"],
                "event_seed_kinds": ["可疑汇款", "挤兑", "保险箱争议"],
            },
            {
                "detail_id": "banking",
                "interior_zones": ["柜台", "经理室", "账簿柜"],
                "profession_ids": ["banker"],
                "service_capabilities": ["存款", "支票", "小额贷款"],
                "record_sources": ["账户账簿", "抵押文件"],
                "access_patterns": ["工作日白天"],
                "investigation_surfaces": ["本地信用关系", "付款痕迹"],
                "event_seed_kinds": ["逾期抵押", "异常提现"],
            },
            {
                "detail_id": "supplies",
                "interior_zones": ["销售区", "柜台", "仓库", "账房"],
                "profession_ids": ["merchant"],
                "service_capabilities": ["日用品", "药品或工具", "订货"],
                "record_sources": ["销售账簿", "订单", "送货单"],
                "access_patterns": ["白天至傍晚营业"],
                "investigation_surfaces": ["特殊采购", "熟客记忆", "包装来源"],
                "event_seed_kinds": ["稀缺物资", "异常订单"],
            },
            {
                "detail_id": "provisions",
                "interior_zones": ["店堂", "柜台", "储藏间"],
                "profession_ids": ["merchant"],
                "service_capabilities": ["基本补给", "订货", "地方消息"],
                "record_sources": ["赊账簿", "订单", "送货记录"],
                "access_patterns": ["白天至傍晚营业"],
                "investigation_surfaces": ["赊账关系", "特殊购买", "店主记忆"],
                "event_seed_kinds": ["断货", "陌生大宗采购"],
            },
            {
                "detail_id": "worship",
                "interior_zones": ["礼拜空间", "办公室", "档案柜", "附属墓地或社区室"],
                "profession_ids": ["clergy"],
                "service_capabilities": ["礼拜", "慈善", "家庭仪式"],
                "record_sources": ["洗礼或出生记录", "婚姻记录", "葬礼记录", "捐赠簿"],
                "access_patterns": ["礼拜时间与预约", "部分档案私人保管"],
                "investigation_surfaces": ["家族关系", "墓碑", "捐赠"],
                "event_seed_kinds": ["档案矛盾", "社区分裂", "被封闭的附属空间"],
            },
            {
                "detail_id": "industrial_district",
                "interior_zones": ["生产区", "办公室", "仓库", "装卸区", "更衣或休息区"],
                "profession_ids": ["industrial_worker", "transport_agent"],
                "service_capabilities": ["生产", "储运", "维修"],
                "record_sources": ["班次表", "货运单", "事故记录", "库存簿"],
                "access_patterns": ["轮班", "危险区和仓库受限"],
                "investigation_surfaces": ["机器痕迹", "货物流向", "工人证词"],
                "event_seed_kinds": ["事故", "失窃货物", "劳资冲突"],
            },
            {
                "detail_id": "school",
                "interior_zones": ["教室", "校务室", "档案柜", "操场"],
                "profession_ids": ["teacher"],
                "service_capabilities": ["教育", "家庭联络"],
                "record_sources": ["学生名册", "出勤记录", "校务通信"],
                "access_patterns": ["学期工作日"],
                "investigation_surfaces": ["家庭关系", "缺勤模式", "教师观察"],
                "event_seed_kinds": ["异常缺勤", "旧校舍传闻"],
            },
            {
                "detail_id": "main_street",
                "interior_zones": ["街道", "店铺门面", "公共告示处"],
                "profession_ids": ["merchant", "law_officer"],
                "service_capabilities": ["商业集散", "公共接触"],
                "record_sources": ["告示", "商家账簿"],
                "access_patterns": ["白天活跃，夜间稀疏"],
                "investigation_surfaces": ["目击者网络", "店铺橱窗", "车辆停靠"],
                "event_seed_kinds": ["公开冲突", "陌生人到来"],
            },
            {
                "detail_id": "community_center",
                "interior_zones": ["公共柜台或聚会区", "储藏处"],
                "profession_ids": ["merchant", "clergy", "rural_resident"],
                "service_capabilities": ["消息交换", "少量补给", "联系外界"],
                "record_sources": ["赊账簿", "公告", "邮件记录"],
                "access_patterns": ["随店主或管理者作息"],
                "investigation_surfaces": ["口述网络", "来客记忆"],
                "event_seed_kinds": ["集会", "传言扩散"],
            },
            {
                "detail_id": "homestead",
                "interior_zones": ["住宅", "谷仓或工棚", "储藏处", "土地边界"],
                "profession_ids": ["rural_resident"],
                "service_capabilities": ["住所", "生产", "临时庇护"],
                "record_sources": ["家庭信件", "账本", "土地文件"],
                "access_patterns": ["私人领地，作息随季节"],
                "investigation_surfaces": ["工具与牲畜", "土地痕迹", "家庭记忆"],
                "event_seed_kinds": ["牲畜异常", "失联住户", "土地争议"],
            },
            {
                "detail_id": "route_landmark",
                "interior_zones": ["道路节点", "桥下或路旁设施"],
                "profession_ids": ["rural_resident", "transport_agent"],
                "service_capabilities": ["导航", "短暂停靠"],
                "record_sources": ["路标", "收费记录", "维修记录"],
                "access_patterns": ["公开但受天气影响"],
                "investigation_surfaces": ["车辙", "足迹", "弃置物"],
                "event_seed_kinds": ["道路损坏", "错误路标", "伏击痕迹"],
            },
            {
                "detail_id": "nearest_services",
                "interior_zones": ["不在本地；指向最近聚落"],
                "profession_ids": ["sheriff", "physician", "merchant"],
                "service_capabilities": ["治安", "医疗", "补给"],
                "record_sources": ["路线与联系方式"],
                "access_patterns": ["必须旅行或发送消息"],
                "investigation_surfaces": ["距离与响应延迟"],
                "event_seed_kinds": ["求援失败", "天气隔绝"],
            },
            {
                "detail_id": "natural_site",
                "interior_zones": ["入口", "主要地貌", "隐蔽区", "危险区"],
                "profession_ids": ["rural_resident"],
                "service_capabilities": ["穿行", "采集", "隐蔽"],
                "record_sources": ["地形图", "土地调查", "口述地名"],
                "access_patterns": ["受天气、季节与地形影响"],
                "investigation_surfaces": ["生物痕迹", "地质与植被", "遗留物"],
                "event_seed_kinds": ["迷路", "自然阻断", "异常痕迹"],
            },
        ],
        "agent_workflow": [
            {
                "stage_id": "select_context",
                "objective": "从已确认年代、地域、聚落规模和环境标签选择 setting pack 与 region pattern。",
                "allowed_inputs": ["campaign setting", "module evidence", "KP selection"],
                "output_records": ["setting selection"],
                "gate": "缺少年代或地域时暂停并请求 KP，不得自行假定。",
            },
            {
                "stage_id": "bind_mentions",
                "objective": "把本子明确提到的地点和机构绑定到功能模板。",
                "allowed_inputs": ["source-bound location mentions", "template aliases"],
                "output_records": ["location-template bindings", "ambiguous matches"],
                "gate": "歧义匹配不得自动绑定。",
            },
            {
                "stage_id": "identify_gaps",
                "objective": "依据聚落模板列出尚未覆盖的核心、典型和条件功能槽位。",
                "allowed_inputs": ["bindings", "settlement template", "condition tags"],
                "output_records": ["missing core slots", "optional candidates"],
                "gate": "缺失槽位只是候选，不是世界事实。",
            },
            {
                "stage_id": "reuse_source_entities",
                "objective": "先把模组已有的人物、组织、物件、文档、交通、事件和线索载体匹配到实体原型。",
                "allowed_inputs": ["source-bound module entities", "entity archetypes"],
                "output_records": ["source entity-archetype bindings", "unresolved matches"],
                "gate": "已有实体优先；歧义保持未解析，不得为同一来源实体再造副本。",
            },
            {
                "stage_id": "fill_candidates",
                "objective": "为选中槽位生成具体建筑名、内部区、职位、服务与作息候选。",
                "allowed_inputs": ["selected slots", "module canon", "era constraints"],
                "output_records": ["scene candidates", "profession candidates"],
                "gate": "不得覆盖模组 Canon，不得生成年代禁用技术。",
            },
            {
                "stage_id": "compose_entities",
                "objective": "只从所选功能槽的实体原型填写必要的局部引用、标签变体、职位、能力和状态候选。",
                "allowed_inputs": ["selected scene candidates", "entity archetype candidates"],
                "output_records": ["typed entity candidates"],
                "gate": "原型不是身份；不得自行创造目录外类型、职位、能力或已确认状态。",
            },
            {
                "stage_id": "link_entities",
                "objective": "把实体关系槽绑定到已有来源实体或同一候选包内的局部引用。",
                "allowed_inputs": ["typed entity candidates", "source entity ids", "relation slots"],
                "output_records": ["relation candidates", "unfilled required relations"],
                "gate": "目标必须可解析且满足种类与数量约束；必需关系未填时阻止落地。",
            },
            {
                "stage_id": "validate",
                "objective": "检查重复实体、关系基数、年代错误、路线断裂、权限和剧情锚点冲突。",
                "allowed_inputs": ["candidate graph", "world facts", "scenario contract"],
                "output_records": ["validation issues", "review packet"],
                "gate": "任何错误或 Canon 冲突都阻止自动落地。",
            },
            {
                "stage_id": "approve_materialize",
                "objective": "通过 AI KP 或真人 KP 共用审批与状态提交内核加入世界。",
                "allowed_inputs": ["approved review packet"],
                "output_records": [
                    "world facts",
                    "locations",
                    "NPC identities",
                    "routes",
                    "audit receipt",
                ],
                "gate": "批准前保持零写入；提交时原子重验版本与事实头。",
            },
        ],
    }
)

BUILTIN_SETTING_PACKS = (US_1920S,)


def get_setting_pack(setting_pack_id: str) -> SettingPack:
    for pack in BUILTIN_SETTING_PACKS:
        if pack.setting_pack_id == setting_pack_id:
            return pack
    raise KeyError(f"Unknown setting pack: {setting_pack_id}")


__all__ = ["BUILTIN_SETTING_PACKS", "US_1920S", "get_setting_pack"]
